"""
MarketBot V2.2 Statistical Validation

Read-only research module for statistical validation of genuine V2
performance observations.

This module does NOT modify:
- V2 production scoring
- factor weights
- database schemas
- production orchestration

It validates results supplied by research.v2_performance.
"""

import math
import random
from statistics import mean, median


def _normal_cdf(x):
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def _normal_two_sided_p(z):
    return 2.0 * (1.0 - _normal_cdf(abs(z)))


def mean_ci_95(values):
    """Approximate 95% confidence interval using a normal approximation."""
    n = len(values)
    if n < 2:
        return None

    avg = mean(values)
    variance = sum((x - avg) ** 2 for x in values) / (n - 1)
    se = math.sqrt(variance / n)

    if se == 0:
        return (avg, avg)

    margin = 1.96 * se
    return avg - margin, avg + margin


def _rank_values(values):
    indexed = sorted(enumerate(values), key=lambda x: x[1])
    ranks = [0.0] * len(values)
    i = 0

    while i < len(indexed):
        j = i
        while j + 1 < len(indexed) and indexed[j + 1][1] == indexed[i][1]:
            j += 1

        rank = (i + j + 2) / 2.0
        for k in range(i, j + 1):
            ranks[indexed[k][0]] = rank

        i = j + 1

    return ranks


def pearson(xs, ys):
    if len(xs) < 2 or len(xs) != len(ys):
        return None

    xb, yb = mean(xs), mean(ys)
    numerator = sum((x - xb) * (y - yb) for x, y in zip(xs, ys))
    xss = sum((x - xb) ** 2 for x in xs)
    yss = sum((y - yb) ** 2 for y in ys)

    denominator = math.sqrt(xss * yss)
    return None if denominator == 0 else numerator / denominator


def spearman(xs, ys):
    if len(xs) < 2 or len(xs) != len(ys):
        return None
    return pearson(_rank_values(xs), _rank_values(ys))


def _permutation_pvalue(xs, ys, statistic, permutations=5000, seed=42):
    """
    Two-sided permutation p-value.

    The observed score is compared with statistics generated by randomly
    permuting returns. This avoids a dependency on scipy and is intended
    as a research diagnostic rather than a production decision rule.
    """
    n = len(xs)

    if n < 3 or len(xs) != len(ys):
        return None

    observed = statistic(xs, ys)
    if observed is None:
        return None

    rng = random.Random(seed)
    shuffled = list(ys)
    extreme = 0

    for _ in range(permutations):
        rng.shuffle(shuffled)
        value = statistic(xs, shuffled)
        if value is not None and abs(value) >= abs(observed):
            extreme += 1

    return (extreme + 1) / (permutations + 1)


def bootstrap_mean_ci(values, iterations=5000, seed=42):
    """Bootstrap 95% CI for the mean."""
    n = len(values)
    if n < 2:
        return None

    rng = random.Random(seed)
    samples = []

    for _ in range(iterations):
        sample = [values[rng.randrange(n)] for _ in range(n)]
        samples.append(mean(sample))

    samples.sort()
    lower_index = int(0.025 * (iterations - 1))
    upper_index = int(0.975 * (iterations - 1))

    return samples[lower_index], samples[upper_index]


def _summary(values):
    if not values:
        return {
            "n": 0,
            "mean": None,
            "median": None,
            "ci_95": None,
        }

    return {
        "n": len(values),
        "mean": mean(values),
        "median": median(values),
        "ci_95": mean_ci_95(values),
    }


def validate(rows, permutations=5000, bootstrap_iterations=5000):
    """
    Validate rows in the same tuple format used by v2_performance:

        trade_date, index_name, sector, rank, intelligence_score, return_5d
    """
    if not rows:
        return {
            "sample_size": 0,
            "status": "INSUFFICIENT_DATA",
            "warning": "No completed genuine V2 outcomes.",
            "pearson": None,
            "pearson_p_value": None,
            "spearman": None,
            "spearman_p_value": None,
            "mean_return": None,
            "mean_return_ci_95": None,
            "bootstrap_mean_ci_95": None,
            "top10_vs_universe_spread": None,
            "spread_summary": None,
            "minimum_sample_guidance": {
                "exploratory": 30,
                "developing": 100,
                "stronger_validation": 200,
            },
        }

    scores = [float(row[4]) for row in rows]
    returns = [float(row[5]) for row in rows]
    top10_returns = [
        float(row[5]) for row in rows if int(row[3]) <= 10
    ]

    p_corr = pearson(scores, returns)
    s_corr = spearman(scores, returns)

    universe_mean = mean(returns)
    top10_mean = mean(top10_returns) if top10_returns else None
    spread = (
        top10_mean - universe_mean
        if top10_mean is not None
        else None
    )

    if len(rows) < 30:
        warning = "Exploratory sample: fewer than 30 completed outcomes."
    elif len(rows) < 100:
        warning = "Developing sample: fewer than 100 completed outcomes."
    elif len(rows) < 200:
        warning = "Initial validation sample: fewer than 200 completed outcomes."
    else:
        warning = None

    return {
        "sample_size": len(rows),
        "status": "VALID",
        "warning": warning,
        "pearson": p_corr,
        "pearson_p_value": _permutation_pvalue(
            scores, returns, pearson, permutations=permutations
        ),
        "spearman": s_corr,
        "spearman_p_value": _permutation_pvalue(
            scores, returns, spearman, permutations=permutations
        ),
        "mean_return": universe_mean,
        "mean_return_ci_95": mean_ci_95(returns),
        "bootstrap_mean_ci_95": bootstrap_mean_ci(
            returns, iterations=bootstrap_iterations
        ),
        "top10_vs_universe_spread": spread,
        "spread_summary": _summary(
            [
                float(row[5]) - universe_mean
                for row in rows
                if int(row[3]) <= 10
            ]
        ),
        "minimum_sample_guidance": {
            "exploratory": 30,
            "developing": 100,
            "stronger_validation": 200,
        },
    }


def run_statistical_validation(db_path=None):
    """Run validation against the genuine V2 outcome dataset."""
    from research.v2_performance import load_v2_outcomes

    rows = load_v2_outcomes(db_path) if db_path else load_v2_outcomes_default()
    result = validate(rows)

    print("\n" + "=" * 78)
    print("MARKETBOT V2.2 STATISTICAL VALIDATION")
    print("=" * 78)
    print(f"Completed genuine V2 outcomes : {result['sample_size']:,}")

    if result["status"] == "INSUFFICIENT_DATA":
        print("\nINSUFFICIENT DATA")
        print(result["warning"])
        print("No statistical significance conclusion is made.")
        print("STATUS: SUCCESS")
        return result

    print(f"Pearson correlation           : {result['pearson']:.4f}")
    print(f"Pearson permutation p-value   : {result['pearson_p_value']:.4f}")
    print(f"Spearman correlation          : {result['spearman']:.4f}")
    print(f"Spearman permutation p-value  : {result['spearman_p_value']:.4f}")
    print(f"Mean 5-day return             : {result['mean_return']:.4f}%")

    ci = result["mean_return_ci_95"]
    boot = result["bootstrap_mean_ci_95"]

    print(
        f"Mean 95% CI                   : "
        f"[{ci[0]:.4f}%, {ci[1]:.4f}%]"
    )
    print(
        f"Bootstrap mean 95% CI         : "
        f"[{boot[0]:.4f}%, {boot[1]:.4f}%]"
    )

    spread = result["top10_vs_universe_spread"]
    print(f"Top-10 vs universe spread     : {spread:.4f}%")

    if result["warning"]:
        print(f"ROBUSTNESS WARNING             : {result['warning']}")

    print("\nSTATUS: SUCCESS")
    return result


def load_v2_outcomes_default():
    from research.v2_performance import load_v2_outcomes
    return load_v2_outcomes()


if __name__ == "__main__":
    run_statistical_validation()
